apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: couchdb-operator
  template:
    metadata:
      labels:
        name: couchdb-operator
    spec:
      serviceAccountName: couchdb-operator
      containers:
        - name: couchdb-operator
          # Replace this with the built image name
          image: srinivasachalla/couchdb-operator:v0.0.4
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - couchdb-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "couchdb-operator"
